site_name: CTGCatalog
site_author: HE Yunye
repo_name: 'GitHub'
repo_url: https://github.com/Cloufield/CTGCatalog/
edit_uri: ""
copyright: "CTGCatalog is licensed under the MIT license"
theme:
  name: material
  features:
    - navigation.tabs
  font:
    code: Roboto Mono
    text: Roboto
  palette:
    primary: indigo
    accent: indigo
extra_css:
  - "stylesheets/extra.css"
markdown_extensions:
  - toc:
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - mkdocs-jupyter
nav: 
    - Home : index.md
    - Tools:
      - Tools: Tools_README.md
      - Drug_discovery: Tools_Drug_discovery_README.md
      - Gene_prioritization: Tools_Gene_prioritization_README.md
      - Polygenic_risk_scores: Tools_Polygenic_risk_scores_README.md
      - Association_tests:
        - Association_tests: Tools_Association_tests_README.md
        - TWAS: Tools_Association_tests_TWAS_README.md
        - sQTL: Tools_Association_tests_sQTL_README.md
        - eQTL: Tools_Association_tests_eQTL_README.md
        - RWAS: Tools_Association_tests_RWAS_README.md
      - Colocalization: Tools_Colocalization_README.md
      - Simulation: Tools_Simulation_README.md
      - Data_processing: Tools_Data_processing_README.md
      - Annotation: Tools_Annotation_README.md
      - Fine_mapping: Tools_Fine_mapping_README.md
      - Gene_set_pathway_analysis: Tools_Gene_set_pathway_analysis_README.md
      - Tissue_and_single_cell: Tools_Tissue_and_single_cell_README.md
      - Imputation: Tools_Imputation_README.md
      - HLA: Tools_HLA_README.md
      - Heritability_and_genetic_correlation: Tools_Heritability_and_genetic_correlation_README.md
      - Proteomics: Tools_Proteomics_README.md
      - GxE_interactions: Tools_GxE_interactions_README.md
      - Mendelian_randomization: Tools_Mendelian_randomization_README.md
      - Meta_and_Multi_triat: Tools_Meta_and_Multi_triat_README.md
    - Sumstats: Sumstats_README.md
    - Reference_data:
      - Reference_data: Reference_data_README.md
      - Biobanks_Cohorts: Reference_data_Biobanks_Cohorts_README.md
      - Protein: Reference_data_Protein_README.md
      - Gene:
        - Gene: Reference_data_Gene_README.md
        - NCBI_refSeq: Reference_data_Gene_NCBI_refSeq_README.md
        - UCSC_refGene:
          - UCSC_refGene: Reference_data_Gene_UCSC_refGene_README.md
          - ucsc_genes: Reference_data_Gene_UCSC_refGene_ucsc_genes_README.md
        - HGNC: Reference_data_Gene_HGNC_README.md
        - knownGenes: Reference_data_Gene_knownGenes_README.md
        - Ensembl: Reference_data_Gene_Ensembl_README.md
        - GENCODE: Reference_data_Gene_GENCODE_README.md
      - Phenotype: Reference_data_Phenotype_README.md
      - Variant: Reference_data_Variant_README.md
      - Epigenomics: Reference_data_Epigenomics_README.md
      - Expression: Reference_data_Expression_README.md
      - Genome:
        - Genome: Reference_data_Genome_README.md
        - hg38: Reference_data_Genome_hg38_README.md
      - xQTL: Reference_data_xQTL_README.md
      - Allele_Frequency: Reference_data_Allele_Frequency_README.md
    - Visualization:
      - Visualization: Visualization_README.md
      - Venn_diagram: Visualization_Venn_diagram_README.md
      - Workflow: Visualization_Workflow_README.md
      - Variants_on_protein: Visualization_Variants_on_protein_README.md
      - Heatmap: Visualization_Heatmap_README.md
