#!/usr/bin/env python3
"""
Regenerate Trending docs from ranking/output/pubmed_baseline_gwas/*.csv.

Writes ``docs/Trending/Trending_PubMed_GWAS.md`` (static tables + iframe), ``docs/Trending/index.md`` (hub),
and ``docs/assets/trending/pubmed_gwas_dashboard.html`` (Plotly + Tabulator: trends + rankings).
The home-page Trending card is generated by ``src/process_homepage.py`` when you
run ``main.py``. Homepage Trending card uses 📑 in ``process_homepage.py``; hub sub-card uses ``ICON_TRENDING_HUB_PUBMED`` below.

    python3 scripts/render_trending_pubmed_gwas.py
    python3 scripts/render_trending_pubmed_gwas.py --stub   # placeholder tables page (no CSV)
"""

from __future__ import annotations

import argparse
import csv
import html
import json
import sys
from collections import defaultdict
from pathlib import Path

# Hub card on docs/Trending/index.md (avoid 📉); homepage uses 📑 in process_homepage.py.
ICON_TRENDING_HUB_PUBMED = "📋"

DASHBOARD_IFRAME_HEIGHT = 1320
DASHBOARD_ASSET_RELPATH = "assets/trending/pubmed_gwas_dashboard.html"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _read_meta(data_dir: Path) -> dict:
    p = data_dir / "run_meta.json"
    if p.is_file():
        return json.loads(p.read_text(encoding="utf-8"))
    return {}


def _table_wrap(inner: str) -> str:
    return (
        '<div class="catalog-summary-table" markdown="block">\n\n'
        f"{inner}\n"
        "</div>\n"
    )


def _trends_table(rows: list[dict[str, str]]) -> str:
    lines = [
        "<table>",
        "<thead><tr><th>Year</th><th>Bucket</th><th>Articles</th></tr></thead>",
        "<tbody>",
    ]
    for r in rows:
        lines.append(
            "<tr>"
            f"<td>{html.escape(r['year'])}</td>"
            f"<td>{html.escape(r['bucket'])}</td>"
            f"<td>{html.escape(r['n_articles'])}</td>"
            "</tr>"
        )
    lines.append("</tbody></table>")
    return _table_wrap("\n".join(lines))


def _journal_volume_table(rows: list[dict[str, str]], max_rows: int) -> str:
    lines = [
        "<table>",
        "<thead><tr>"
        "<th>Rank</th><th>Journal</th><th>GWAS hits</th><th>Total</th><th>Fraction</th>"
        "</tr></thead>",
        "<tbody>",
    ]
    for r in rows[:max_rows]:
        lines.append(
            "<tr>"
            f"<td>{html.escape(r['rank_volume'])}</td>"
            f"<td title=\"{html.escape(r['full_title'], quote=True)}\">"
            f"{html.escape(r['journal_key'])}</td>"
            f"<td>{html.escape(r['gwas_hits'])}</td>"
            f"<td>{html.escape(r['total_articles'])}</td>"
            f"<td>{html.escape(r['fraction_gwas'])}</td>"
            "</tr>"
        )
    lines.append("</tbody></table>")
    return _table_wrap("\n".join(lines))


def _journal_share_table(rows: list[dict[str, str]], max_rows: int) -> str:
    lines = [
        "<table>",
        "<thead><tr>"
        "<th>Rank</th><th>Journal</th><th>GWAS hits</th><th>Total</th><th>Fraction</th>"
        "</tr></thead>",
        "<tbody>",
    ]
    for r in rows[:max_rows]:
        lines.append(
            "<tr>"
            f"<td>{html.escape(r['rank_share'])}</td>"
            f"<td title=\"{html.escape(r['full_title'], quote=True)}\">"
            f"{html.escape(r['journal_key'])}</td>"
            f"<td>{html.escape(r['gwas_hits'])}</td>"
            f"<td>{html.escape(r['total_articles'])}</td>"
            f"<td>{html.escape(r['fraction_gwas'])}</td>"
            "</tr>"
        )
    lines.append("</tbody></table>")
    return _table_wrap("\n".join(lines))


def _load_csv(path: Path) -> list[dict[str, str]]:
    if not path.is_file():
        return []
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _group_by_year(rows: list[dict[str, str]], year_key: str) -> dict[str, list[dict[str, str]]]:
    g: dict[str, list[dict[str, str]]] = defaultdict(list)
    for r in rows:
        g[r[year_key]].append(r)
    return dict(g)


def _json_for_script(payload: dict) -> str:
    s = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return s.replace("<", "\\u003c")


def _journal_payload_rows(
    rows: list[dict[str, str]], rank_field: str, limit: int
) -> list[dict]:
    out: list[dict] = []
    for r in rows[:limit]:
        fr = (r.get("fraction_gwas") or "").strip() or "0"
        try:
            f = float(fr)
        except ValueError:
            f = 0.0
        out.append(
            {
                "rank": int(r[rank_field]),
                "journal_key": r["journal_key"],
                "full_title": r.get("full_title", r["journal_key"]),
                "gwas_hits": int(r["gwas_hits"]),
                "total_articles": int(r["total_articles"]),
                "fraction_gwas": round(f, 6),
            }
        )
    return out


def _build_dashboard_payload(
    trends_rows: list[dict[str, str]],
    vol_rows: list[dict[str, str]],
    share_rows: list[dict[str, str]],
    *,
    table_limit: int,
    bar_top_n: int,
) -> dict:
    trends_json = [
        {"year": int(r["year"]), "bucket": r["bucket"], "n_articles": int(r["n_articles"])}
        for r in trends_rows
    ]
    vol_lim = _journal_payload_rows(vol_rows, "rank_volume", table_limit)
    share_lim = _journal_payload_rows(share_rows, "rank_share", table_limit)
    bar_slice = vol_rows[:bar_top_n]
    bar_json = [
        {
            "journal_key": r["journal_key"],
            "gwas_hits": int(r["gwas_hits"]),
            "full_title": r.get("full_title", ""),
        }
        for r in bar_slice
    ]
    return {
        "trends": trends_json,
        "journal_volume": vol_lim,
        "journal_share": share_lim,
        "journal_volume_bar": bar_json,
    }


def write_interactive_dashboard_html(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    inj = _json_for_script(payload)
    html_doc = (
        """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>PubMed GWAS — interactive</title>
<link href="https://unpkg.com/tabulator-tables@6.2.5/dist/css/tabulator.min.css" rel="stylesheet"/>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js" charset="utf-8"></script>
<style>
body{font-family:system-ui,-apple-system,sans-serif;margin:0;padding:14px 16px 32px;background:#f1f5f9;color:#0f172a;font-size:14px;}
h2{font-size:1.05rem;margin:1.4em 0 .45em;font-weight:650;color:#1e3a8a;}
h2:first-of-type{margin-top:.25em;}
.chart{width:100%;min-height:320px;}
.tab-wrap{margin-top:8px;border-radius:10px;overflow:hidden;background:#fff;box-shadow:0 1px 3px rgba(15,23,42,.12);}
@media (prefers-color-scheme:dark){
body{background:#0f172a;color:#e2e8f0;}
h2{color:#93c5fd;}
.tab-wrap{background:#1e293b;}
}
</style>
</head>
<body>
<h2>Articles per year by keyword bucket</h2>
<p style="margin:0 0 8px;opacity:.85;font-size:13px;">Each line is one bucket; the same paper can count toward more than one bucket.</p>
<div id="plot-trends" class="chart"></div>
<h2>Top journals by GWAS-related volume</h2>
<div id="plot-journals" class="chart"></div>
<h2>Journal rankings</h2>
<p style="margin:0 0 8px;opacity:.85;font-size:13px;">Sort by clicking a column header; adjust page size at the bottom.</p>
<h2 style="margin-top:1em;">By GWAS-related hits (full window)</h2>
<div id="table-vol" class="tab-wrap"></div>
<h2>By fraction GWAS-related (qualifying journals)</h2>
<div id="table-share" class="tab-wrap"></div>
<script type="application/json" id="gwas-dash-payload">"""
        + inj
        + """</script>
<script src="https://unpkg.com/tabulator-tables@6.2.5/dist/js/tabulator.min.js"></script>
<script>
(function(){
var el=document.getElementById("gwas-dash-payload");
if(!el)return;
var D=JSON.parse(el.textContent);
var years=[...new Set(D.trends.map(function(t){return t.year;}))].sort(function(a,b){return a-b;});
var bucketNames=[...new Set(D.trends.map(function(t){return t.bucket;}))].sort();
var byBk={};
for(var i=0;i<D.trends.length;i++){var t=D.trends[i];if(!byBk[t.bucket])byBk[t.bucket]={};byBk[t.bucket][t.year]=t.n_articles;}
var traces=bucketNames.map(function(b){return{x:years,y:years.map(function(y){return byBk[b][y]||0;}),name:b,mode:"lines+markers",type:"scatter"};});
Plotly.newPlot("plot-trends",traces,{xaxis:{title:"Year",dtick:1},yaxis:{title:"Articles"},legend:{orientation:"h",y:-0.28,yanchor:"top"},margin:{t:24,b:120,l:56,r:20},paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)"},{responsive:true,displayModeBar:true,displaylogo:false});
var barSrc=D.journal_volume_bar.slice().reverse();
Plotly.newPlot("plot-journals",[{type:"bar",orientation:"h",x:barSrc.map(function(d){return d.gwas_hits;}),y:barSrc.map(function(d){return d.journal_key;}),marker:{color:"#2563eb"},text:barSrc.map(function(d){return d.gwas_hits;}),textposition:"outside"}],{xaxis:{title:"GWAS-related articles"},margin:{l:200,r:70,t:16,b:48},height:Math.max(400,barSrc.length*22),paper_bgcolor:"rgba(0,0,0,0)",plot_bgcolor:"rgba(0,0,0,0)"},{responsive:true,displayModeBar:true,displaylogo:false});
var colCommon=[{title:"Rank",field:"rank",width:68,sorter:"number"},{title:"Journal",field:"journal_key",widthGrow:2,minWidth:120},{title:"Full title",field:"full_title",widthGrow:3,minWidth:160},{title:"GWAS hits",field:"gwas_hits",hozAlign:"right",sorter:"number"},{title:"Total",field:"total_articles",hozAlign:"right",sorter:"number"},{title:"Fraction",field:"fraction_gwas",hozAlign:"right",sorter:"number",formatter:function(c){var v=c.getValue();return v==null?"":Number(v).toFixed(4);}}];
new Tabulator("#table-vol",{data:D.journal_volume,columns:colCommon,height:"420px",layout:"fitColumns",pagination:"local",paginationSize:15,paginationSizeSelector:[10,15,25,50,100,200],paginationCounter:"rows"});
new Tabulator("#table-share",{data:D.journal_share,columns:colCommon,height:"420px",layout:"fitColumns",pagination:"local",paginationSize:15,paginationSizeSelector:[10,15,25,50,100,200],paginationCounter:"rows"});
})();
</script>
</body>
</html>"""
    )
    path.write_text(html_doc, encoding="utf-8")


def write_stub_dashboard_html(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/><title>PubMed GWAS — no data</title>
<style>body{font-family:system-ui,sans-serif;padding:20px;max-width:40em;}</style>
</head><body>
<p><strong>No dashboard data.</strong> Run <code>scripts/pubmed_baseline_gwas.py</code> on your PubMed baseline, then
<code>scripts/render_trending_pubmed_gwas.py</code> from the repo root.</p>
</body></html>
""",
        encoding="utf-8",
    )


def _methods_section_md() -> str:
    return "\n".join(
        [
            "## Methods",
            "",
            "Counts are derived offline from **NCBI PubMed baseline** Medline XML (gzip shards such as `pubmed*.xml.gz`), streamed with `xml.etree.ElementTree.iterparse` so memory stays bounded; optional workers process files in parallel and results are merged from per-file JSON shards.",
            "",
            "**Publication year** comes from `JournalIssue.PubDate` (or `ArticleDate` when needed). **Journal** is keyed by `MedlineJournalInfo.MedlineTA` when present, otherwise ISO abbreviation or full journal title.",
            "",
            "**Trend buckets (per year):** *MeSH_GWAS* counts articles whose MeSH descriptor name contains “genome-wide association”. *text_GWAS_core*, *text_PRS*, and *text_MR* count articles whose **title, abstract, and author keywords** match fixed case-insensitive patterns (e.g. “GWAS”, “genome-wide association”, polygenic risk/score, Mendelian randomization). An article can contribute to more than one text bucket.",
            "",
            "**Journal GWAS-related counts** use a single article-level flag: MeSH_GWAS **or** *text_GWAS_core* only (PRS/MR text alone does not count toward journal volume/share). **Share** rankings restrict to journals with at least one such hit and a minimum article count in the window (overall or per calendar year, as noted above).",
            "",
            "Implementation: `scripts/pubmed_baseline_gwas.py`; tables and dashboard: `scripts/render_trending_pubmed_gwas.py`.",
            "",
        ]
    )


def _dashboard_iframe_md() -> str:
    rel = f"../../{DASHBOARD_ASSET_RELPATH}"
    h = DASHBOARD_IFRAME_HEIGHT
    return "\n".join(
        [
            "## Interactive dashboard",
            "",
            "Charts: use the Plotly toolbar to pan/zoom; hover points for values. Tables: click column headers to sort; change page size in the footer.",
            "",
            '<div class="trending-dashboard-frame-wrap" markdown="0">',
            f'<iframe class="trending-dashboard-frame" src="{rel}" '
            'title="PubMed GWAS interactive trends and journal rankings" '
            f'width="100%" height="{h}" '
            'style="border:0;border-radius:10px;box-shadow:0 2px 12px rgba(15,23,42,.1);"></iframe>',
            "</div>",
            "",
        ]
    )


def write_trending_hub_md(path: Path, icon_pubmed: str) -> None:
    path.write_text(
        "\n".join(
            [
                "---",
                "hide:",
                "- navigation",
                "- tags",
                "tags:",
                "- Statistics",
                "- GWAS",
                "---",
                "",
                "# Trending",
                "",
                "Derived statistics and literature trends from public corpora "
                "(not the main curated catalog tables).",
                "",
                '<div class="grid cards catalog-home-cards">',
                "<ul>",
                "<li>",
                '<a class="catalog-home-card-link" href="Trending_PubMed_GWAS/">',
                f'<p><span class="catalog-card-icon" aria-hidden="true">{icon_pubmed}</span> '
                "<strong>PubMed — GWAS literature</strong></p>",
                "<hr>",
                "<p>Term trends and journal rankings from PubMed baseline "
                "(GWAS-related MeSH and text buckets).</p>",
                "</a>",
                "</li>",
                "</ul>",
                "</div>",
                "",
            ]
        ),
        encoding="utf-8",
    )


def write_stub_trending_pubmed(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "---",
                "hide:",
                "- tags",
                "tags:",
                "- Statistics",
                "- GWAS",
                "class: catalog-section-Trending",
                "---",
                "",
                "# PubMed — GWAS literature",
                "",
                "!!! note \"Tables not generated\"",
                "    No CSV bundle was found under `ranking/output/pubmed_baseline_gwas/`.",
                "    Run `scripts/pubmed_baseline_gwas.py` on your PubMed baseline, then:",
                "    ",
                "    ```bash",
                "    python3 scripts/render_trending_pubmed_gwas.py",
                "    ```",
                "",
                _dashboard_iframe_md(),
                "The embedded dashboard will show a short message until data are generated.",
                "",
                _methods_section_md(),
            ]
        ),
        encoding="utf-8",
    )


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--data-dir",
        type=Path,
        default=None,
        help="Directory with CSV outputs (default: <repo>/ranking/output/pubmed_baseline_gwas)",
    )
    ap.add_argument(
        "--top-volume",
        type=int,
        default=40,
        help="Rows for overall volume table",
    )
    ap.add_argument(
        "--top-share",
        type=int,
        default=40,
        help="Rows for overall share table",
    )
    ap.add_argument(
        "--top-per-year",
        type=int,
        default=20,
        help="Rows per year for by-year tables",
    )
    ap.add_argument(
        "--stub",
        action="store_true",
        help="Write placeholder PubMed page + hub only (no CSV required)",
    )
    ap.add_argument(
        "--dashboard-table-limit",
        type=int,
        default=250,
        help="Max rows per ranking table in the interactive dashboard",
    )
    ap.add_argument(
        "--dashboard-bar-top",
        type=int,
        default=35,
        help="Number of journals in the horizontal bar chart",
    )
    args = ap.parse_args()
    root = _repo_root()
    data_dir = (
        args.data_dir.expanduser().resolve()
        if args.data_dir
        else root / "ranking/output/pubmed_baseline_gwas"
    )
    out_path = root / "docs/Trending/Trending_PubMed_GWAS.md"
    hub_path = root / "docs/Trending/index.md"

    dash_path = root / "docs" / DASHBOARD_ASSET_RELPATH

    out_path.parent.mkdir(parents=True, exist_ok=True)

    if args.stub:
        write_stub_dashboard_html(dash_path)
        print(f"Wrote stub {dash_path}", file=sys.stderr)
        write_stub_trending_pubmed(out_path)
        print(f"Wrote stub {out_path}", file=sys.stderr)
        write_trending_hub_md(hub_path, ICON_TRENDING_HUB_PUBMED)
        print(f"Wrote {hub_path}", file=sys.stderr)
        return 0

    if not (data_dir / "gwas_trends_by_year.csv").is_file():
        print(f"Missing CSV under {data_dir}; run pubmed_baseline_gwas.py or use --stub.", file=sys.stderr)
        return 1

    meta = _read_meta(data_dir)
    trends = _load_csv(data_dir / "gwas_trends_by_year.csv")
    vol = _load_csv(data_dir / "journal_gwas_ranking.csv")
    share = _load_csv(data_dir / "journal_gwas_ranking_by_share.csv")
    vol_y = _load_csv(data_dir / "journal_gwas_ranking_by_year.csv")
    share_y = _load_csv(data_dir / "journal_gwas_ranking_by_share_by_year.csv")

    dash_payload = _build_dashboard_payload(
        trends,
        vol,
        share,
        table_limit=max(1, args.dashboard_table_limit),
        bar_top_n=max(5, args.dashboard_bar_top),
    )
    write_interactive_dashboard_html(dash_path, dash_payload)
    print(f"Wrote {dash_path}", file=sys.stderr)

    ym, yx = meta.get("year_min", "?"), meta.get("year_max", "?")
    n_shards = meta.get("n_baseline_files", "?")
    n_j = meta.get("n_journals_any", "?")

    lines: list[str] = [
        "---",
        "hide:",
        "- tags",
        "tags:",
        "- Statistics",
        "- GWAS",
        "class: catalog-section-Trending",
        "---",
        "",
        '<div class="catalog-nav-lead" markdown="block">',
        "",
        f"**PubMed baseline** snapshot: indexed article counts for GWAS-related **MeSH** and **title/abstract** buckets, plus journal rankings (volume and share), for publication years **{ym}–{yx}**.",
        "",
        "</div>",
        "",
        "## Provenance",
        "",
        f"- **Baseline files merged:** {n_shards}",
        f"- **Distinct journals (any row):** {n_j}",
        "- **Share ranking** includes only journals with at least one GWAS-related hit and ≥ 50 articles in the window (overall) or in that calendar year (by-year tables).",
        "- Regenerate this page after re-running `scripts/pubmed_baseline_gwas.py` and `scripts/render_trending_pubmed_gwas.py`.",
        "- Interactive assets: `docs/assets/trending/pubmed_gwas_dashboard.html` (regenerated with this script).",
        "",
        _dashboard_iframe_md(),
        "## Static tables (export / print)",
        "",
        "The same numbers as in the dashboard, as plain sortable tables on this page.",
        "",
        "## Term trends by year",
        "",
        "*MeSH_GWAS* = MeSH descriptor for genome-wide association; *text_* buckets match title, abstract, or author keywords.",
        "",
        "*Click a column header to sort.*",
        "",
        _trends_table(trends),
        "",
        "## Journals — by GWAS-related volume (full window)",
        "",
        f"*Top {args.top_volume} by number of GWAS-related articles (MeSH or core text match).*",
        "",
        "*Click a column header to sort.*",
        "",
        _journal_volume_table(vol, args.top_volume),
        "",
        "## Journals — by GWAS share (full window)",
        "",
        f"*Top {args.top_share} by fraction of articles that are GWAS-related (among journals with ≥ 50 articles and ≥ 1 GWAS hit).*",
        "",
        "*Click a column header to sort.*",
        "",
        _journal_share_table(share, args.top_share),
        "",
    ]

    by_vol = _group_by_year(vol_y, "year")
    by_sh = _group_by_year(share_y, "year")
    years = sorted(set(by_vol) | set(by_sh), key=int)

    lines += [
        "## By calendar year",
        "",
        f"*Within each year: top {args.top_per_year} by volume, then by share (same eligibility as above).*",
        "",
    ]

    for y in years:
        vrows = sorted(
            by_vol.get(y, []),
            key=lambda r: int(r.get("rank_volume", "0")),
        )[: args.top_per_year]
        srows = sorted(
            by_sh.get(y, []),
            key=lambda r: int(r.get("rank_share", "0")),
        )[: args.top_per_year]
        lines += [
            f"### {y}",
            "",
            "#### Volume (GWAS-related hits)",
            "",
            "*Click a column header to sort.*",
            "",
            _journal_volume_table(vrows, args.top_per_year),
            "",
            "#### Share (among qualifying journals)",
            "",
            "*Click a column header to sort.*",
            "",
            _journal_share_table(srows, args.top_per_year),
            "",
        ]

    lines.append(_methods_section_md())

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}", file=sys.stderr)

    write_trending_hub_md(hub_path, ICON_TRENDING_HUB_PUBMED)
    print(f"Wrote {hub_path}", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
